---
- name: Configure system | Tasks
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: User tasks
      ansible.builtin.import_tasks: "tasks/users.yml"

    - name: Packages tasks
      ansible.builtin.import_tasks: "tasks/packages.yml"

    - name: Config tasks
      ansible.builtin.import_tasks: "tasks/dotfiles.yml"

- name: Configure system | Nvidia
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: nvidia
      when: nvidia == true

- name: Configure caps2esc
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: caps2esc
