---
- name: Configure users and groups
  hosts: localhost
  connection: local
  become: true
  roles:
    - users

- name: Install/Update packages
  hosts: localhost
  connection: local
  become: true
  roles:
    - packages

- name: Configure system and services
  hosts: localhost
  connection: local
  become: true
  roles:
    - configs

