---
- name: Configure system
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: User tasks
      ansible.builtin.import_tasks: "tasks/users.yml"

    - name: Packages tasks
      ansible.builtin.import_tasks: "tasks/packages.yml"

    - name: Config tasks
      ansible.builtin.import_tasks: "tasks/dotfiles.yml"

