---
- name: Config dirs present
  block:

    - name: KDE config dirs present
      ansible.builtin.file:
        path: "/home/{{ user.username }}/.kde"
        state: directory
        owner: "{{ user.username }}"
        group: "{{ user.groupname }}"
        mode: '0700'
      loop: "{{ kde_users|flatten(levels=1) }}"
      loop_control:
        loop_var: user

    - name: User config dirs present
      ansible.builtin.file:
        path: "/home/{{ user.username }}/.config"
        state: directory
        owner: "{{ user.username }}"
        group: "{{ user.groupname }}"
        mode: '0700'
      loop: "{{ zsh_users|flatten(levels=1) }}"
      loop_control:
        loop_var: user

# TODO: Add dotfile repo cloning and symlinking

