- name: Groups configured
  ansible.builtin.group:
    name: "{{ group.groupname }}"
    gid: "{{ group.gid }}"
  loop: "{{ local_groups|flatten(levels=1) }}"
  loop_control:
    loop_var: group

- name: Users configured
  ansible.builtin.user:
    name: "{{ user.username }}"
    uid: "{{ user.uid }}"
    groups: "{{ user.groups }}"
    shell: "{{ user.shell }}"
  loop: "{{ users|flatten(levels=1) }}"
  loop_control:
    loop_var: user

- name: Group 'wheel' can sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: /usr/sbin/visudo -cf %s

