---
- name: Nvidia packages present and up to date
  ansible.builtin.package:
    name:
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
    state: present
    update_cache: true

- name: Pacman hooks dir present
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: '0644'

- name: Nvidia Pacman hook present
  ansible.builtin.copy:
    src: nvidia.hook
    dest: /etc/pacman.d/hooks/nvidia.hook

- name: Nvidia DRM kernel mode set
  ansible.builtin.copy:
    src: nvidia.conf
    dest: /etc/modprobe.d/nvidia.conf

- name: Nvidia services enabled
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - nvidia-suspend.service
    - nvidia-hibernate.service
    - nvidia-resume.service

