- name: Configure users
  ansible.builtin.user:
    name: "{{ user.username }}"
    uid: "{{ user.uid }}"
    groups: "{{ user.groups }}"
    shell: "{{ user.shell }}"
  loop: "{{ users|flatten(levels=1) }}"
  loop_control:
    loop_var: user

- name: Configure groups
  ansible.builtin.group:
    name: "{{ group.groupname }}"
    gid: "{{ group.gid }}"
  loop: "{{ local_groups|flatten(levels=1) }}"
  loop_control:
    loop_var: group


